[project]
name = "mojodep-colcon"
version = "0.1.0"
description = "Colcon interop for mojodep"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mojodep-core",
    "mojodep-git",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mojodep_colcon"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"
]

[tool.uv.sources]
mojodep-git = { workspace = true }
