[project]
name = "mojodep-git"
version = "0.1.0"
description = "Git interop for mojodep"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mojodep-core",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mojodep_git"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"
]
