# This workflow will install Python dependencies, run tests, lint and upload the results to SonarQube.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# This name shows up in status badges, so a concise one is better.
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  UV_VERSION: "0.5.10"
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install basic tools
        run: |
          apt-get update && apt-get install -qq unzip curl
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev --all-packages
      - name: Lint with Ruff
        run: |
          uvx ruff check --output-format=github .;
          uvx ruff check --output-file=ruff.json --output-format=json .
      - name: Type check with ty
        run: |
          uvx ty check
      - name: Test with pytest
        if: success() || failure()
        run: |
          uv run pytest --cov --cov-report=xml --junit-xml=pytest-results.xml
      - name: Build Package
        if: success()
        run: |
          uv build

      - name: Export requirements.txt
        run: |
          uv export --frozen --no-hashes --no-emit-workspace --no-dev --all-packages \
            | tee dist/requirements.txt

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/*
      
